<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('films')->insert([
              [
                'id' => 1,
                'titre' => 'The Godfather',
                'resume' => 'Lhistoire épique dune famille mafieuse italienne aux États-Unis.',
                'affiche' => '../images/films/godfather.jpg',
                'duree' => '2h55min',
                'realisateur_id' => 11,
                'producteur_id' => 11,
                'acteur_id' => 3,
                'annee' => 1972,
                'cote' => '4,9 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/UaVTIH8mujA',
                'audience' => 18
            ],
            [
                'id' => 2,
                'titre' => 'Fight Club',
                'resume' => 'Un homme déçu crée un club secret de combat dans le sous-sol dun bar.',
                'affiche' => '../images/films/fightclub.jpg',
                'duree' => '2h19min',
                'realisateur_id' => 12, 
                'producteur_id' => 13,
                'acteur_id' => 20,
                'annee' => 1999,
                'cote' => '4,7 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/BdJKm16Co6M',
                'audience' => 18
            ],
              [
                'id' => 3,
                'titre' => 'Inception',
                'resume' => 'Un voleur délite vole des informations en infiltrant les rêves de ses cibles.',
                'affiche' => '../images/films/inception.jpg',
                'duree' => '2h28min',
                'realisateur_id' => 1, 
                'producteur_id' => 1, 
                'acteur_id' => 1,
                'annee' => 2010,
                'cote' => '4 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/HcoZbHBDHQA',
                'audience' => 16
            ],
            [
                'id' => 4,
                'titre' => 'Interstellar',
                'resume' => 'Un groupe dexplorateurs part à la recherche dune nouvelle planète pour sauver lhumanité.',
                'affiche' => '../images/films/interstellar.jpg',
                'duree' => '2h49min',
                'realisateur_id' => 1, 
                'producteur_id' => 1, 
                'acteur_id' => 4,
                'annee' => 2014,
                'cote' => '4,5 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/HsPP6xSzQoE',
                'audience' => 12
            ],
            [
                'id' => 5,
                'titre' => 'Avatar',
                'resume' => 'Un paraplégique est envoyé sur la planète Pandora pour participer à un programme dexploration.',
                'affiche' => '../images/films/avatar.jpg',
                'duree' => '2h42min',
                'realisateur_id' => 14, 
                'producteur_id' => 14, 
                'acteur_id' => 5,
                'annee' => 2009,
                'cote' => '4 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/5PSNL1qE6VY',
                'audience' => 10
            ],
            [
                'id' => 6,
                'titre' => 'The Dark Knight',
                'resume' => 'Batman affronte le Joker, un criminel psychotique.',
                'affiche' => '../images/films/darkknight.jpg',
                'duree' => '2h32min',
                'realisateur_id' => 1, 
                'producteur_id' => 1, 
                'acteur_id' => 6,
                'annee' => 2008,
                'cote' => '4,5 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
                'audience' => 16
            ],
            [
              'id' => 7,
              'titre' => 'Pulp Fiction',
              'resume' => 'Des histoires entrelacées de criminels, de gangsters et de boxeurs à Los Angeles.',
              'affiche' => '../images/films/pulpfiction.jpg',
              'duree' => '2h34min',
              'realisateur_id' => 10,
              'producteur_id' => 15,
              'acteur_id' => 7,
              'annee' => 1994,
              'cote' => '4,5 étoiles',
              'categorie' => 'classique',
              'bandeAnnonce' => 'https://www.youtube.com/embed/EXeTwQWrcwY',
              'audience' => 18
            ],
            [
                'id' => 8,
                'titre' => 'The Shawshank Redemption',
                'resume' => "Un homme injustement condamné à perpétuité forme une amitié unique en prison.",
                'affiche' => '../images/films/shawshank.jpg',
                'duree' => '2h22min',
                'realisateur_id' => 2,
                'producteur_id' => 16,
                'acteur_id' => 8,
                'annee' => 1994,
                'cote' => '4,8 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/NmzuHjWmXOc',
                'audience' => 16
            ],
            [
                'id' => 9,
                'titre' => 'The Lord of the Rings: The Fellowship of the Ring',
                'resume' => 'Un jeune hobbit entreprend un voyage épique pour détruire un anneau maléfique.',
                'affiche' => '../images/films/thelordoftherings.jpg',
                'duree' => '2h58min',
                'realisateur_id' => 3,
                'producteur_id' => 3,
                'acteur_id' => 9,
                'annee' => 2000,
                'cote' => '4,7 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/nalLU8i4zgs',
                'audience' => 12
            ],
            [
                'id' => 10,
                'titre' => 'The Matrix Reloaded',
                'resume' => 'La suite de "La Matrice" avec de nouvelles aventures de Neo et ses alliés.',
                'affiche' => '../images/films/matrixreloaded.jpg',
                'duree' => '2h18min',
                'realisateur_id' => 4,
                'producteur_id' => 8,
                'acteur_id' => 10,
                'annee' => 2003,
                'cote' => '4 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/kYzz0FSgpSU',
                'audience' => 12
            ],
            [
                'id' => 11,
                'titre' => 'Stranger Things',
                'resume' => 'Une série de science-fiction qui se déroule dans les années 1980, où un groupe damis se lance à la recherche de leur ami d isparu, en rencontrant des phénomènes surnaturels et un laboratoire gouvernemental secret.',
                'affiche' => '../images/films/strangerthings.jpg',
                'duree' => '4 saisons',
                'realisateur_id' => 17,
                'producteur_id' => 17,
                'acteur_id' => 23,
                'annee' => 2016,
                'cote' => '4,5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/b9EkMc79ZSU',
                'audience' => 12
            ],
            
            [
                'id' => 12,
                'titre' => 'Black Mirror: Bandersnatch',
                'resume' => 'Un film interactif de science-fiction qui permet aux spectateurs de prendre des décisions pour le protagoniste, Stefan, alors qu il travaille sur un jeu vidéo basé sur un livre déroutant.',
                'affiche' => '../images/films/blackmirror.jpg',
                'duree' => '1h30min (variable)',
                'realisateur_id' => 18,
                'producteur_id' => 18,
                'acteur_id' => 24,
                'annee' => 2018,
                'cote' => '4,5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/vP_VhBFdN4U',
                'audience' => 16
            ],
            [
                'id' => 13,
                'titre' => 'Breaking Bad',
                'resume' => 'Un professeur de chimie diagnostiqué dun cancer se tourne vers la fabrication et la vente de méthamphétamine pour assurer lavenir financier de sa famille. Il plonge dans le monde du crime.',
                'affiche' => '../images/films/breakingbad.jpg',
                'duree' => '5 saisons',
                'realisateur_id' => 19,
                'producteur_id' => 19,
                'acteur_id' => 21,
                'annee' => 2008,
                'cote' => '5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/HhesaQXLuRY',
                'audience' => 16
            ],
            [
                'id' => 14,
                'titre' => 'The Witcher',
                'resume' => 'Geralt de Riv, un chasseur de monstres surnaturels, se bat pour trouver sa place dans un monde où les humains se révèlent souvent plus monstrueux que les créatures qu il chasse.',
                'affiche' => '../images/films/thewitcher.jpg',
                'duree' => '2 saisons',
                'realisateur_id' => 20,
                'producteur_id' => 20,
                'acteur_id' => 11,
                'annee' => 2019,
                'cote' => '4,5 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/ndl1W4ltcmg',
                'audience' => 16
            ],
            [
                'id' => 15,
                'titre' => 'La La Land',
                'resume' => 'Lhistoire de Mia, une aspirante actrice, et Sebastian, un musicien de jazz, qui tombent amoureux à Los Angeles tout en poursuivant leurs rêves artistiques.',
                'affiche' => '../images/films/lalaland.jpg',
                'duree' => '2h8min',
                'realisateur_id' => 21,
                'producteur_id' => 21,
                'acteur_id' => 22,
                'annee' => 2016,
                'cote' => '4,5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/0pdqf4P9MB8',
                'audience' => 8
            ],
            
            [
                'id' => 16,
                'titre' => 'The Crown',
                'resume' => 'Une série dramatique qui retrace la vie de la reine Elizabeth II depuis ses débuts jusquà nos jours, mettant en lumière les événements historiques majeurs et les complexités de la monarchie britannique.',
                'affiche' => '../images/films/thecrown.jpg',
                'duree' => '5 saisons',
                'realisateur_id' => 22,
                'producteur_id' => 22,
                'acteur_id' => 25,
                'annee' => 2016,
                'cote' => '4,5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/JWtnJjn6ng0',
                'audience' => 10
            ],
            
            [
                'id' => 17,
                'titre' => 'Jurassic Park',
                'resume' => 'Un milliardaire crée un parc dattractions rempli de dinosaures clonés, mais les choses tournent mal lorsque les dinosaures séchappent et menacent les visiteurs.',
                'affiche' => '../images/films/jurassicpark.jpg',
                'duree' => '2h7min',
                'realisateur_id' => 23,
                'producteur_id' => 23,
                'acteur_id' => 12,
                'annee' => 1993,
                'cote' => '4 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/lc0UehYemQA',
                'audience' => 10
            ],
            [
                'id' => 18,
                'titre' => 'Friends',
                'resume' => 'Une série comique mettant en scène un groupe damis à New York alors quils traversent les hauts et les bas de la vie, les relations et les carrières.',
                'affiche' => '../images/films/friends.jpg',
                'duree' => '10 saisons',
                'realisateur_id' => 24,
                'producteur_id' => 24,
                'acteur_id' => 26,
                'annee' => 1994,
                'cote' => '4,5 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/IEEbUzffzrk',
                'audience' => 8
            ],
            
            [
                'id' => 19,
                'titre' => 'Gladiator',
                'resume' => 'Lhistoire de Maximus, un général romain déchu qui cherche à se venger de lempereur corrompu qui a assassiné sa famille et la condamné à lesclavage.',
                'affiche' => '../images/films/gladiator.jpg',
                'duree' => '2h35min',
                'realisateur_id' => 25,
                'producteur_id' => 25,
                'acteur_id' => 13,
                'annee' => 2000,
                'cote' => '4,5 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/P5ieIbInFpg',
                'audience' => 16
            ],
            [
                'id' => 20,
                'titre' => 'Game of Thrones',
                'resume' => 'Une série médiévale-fantastique basée sur les romans de George R.R. Martin. Elle suit les intrigues politiques et les conflits de puissance entre les grandes familles des Sept Couronnes de Westeros.',
                'affiche' => '../images/films/gameofthrones.jpg',
                'duree' => '8 saisons',
                'realisateur_id' => 27,
                'producteur_id' => 27,
                'acteur_id' => 27,
                'annee' => 2011,
                'cote' => '4,5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/KPLWWIOCOOQ',
                'audience' => 18
            ],
            [
                'id' => 21,
                'titre' => 'The Great Gatsby',
                'resume' => "L'histoire de Jay Gatsby, un homme mystérieux et richissime qui organise de somptueuses fêtes à Long Island dans les années 1920. Le film explore la fascination, la richesse et les excès de l'époque.",
                'affiche' => '../images/films/gatsby.jpg',
                'duree' => '2h23min',
                'realisateur_id' => 28,
                'producteur_id' => 28,
                'acteur_id' => 1,
                'annee' => 2013,
                'cote' => '4 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/rARN6agiW7o',
                'audience' => 10
            ],
            [
                'id' => 22,
                'titre' => 'Inglourious Basterds',
                'resume' => 'Dans la France occupée par les nazis, un groupe de soldats juifs américains connus sous le nom de "Basterds" mène une vendetta brutale contre les nazis.',
                'affiche' => '../images/films/ingloriousbasterds.jpg',
                'duree' => '2h33min',
                'realisateur_id' => 10,
                'producteur_id' => 15,
                'acteur_id' => 20,
                'annee' => 2009,
                'cote' => '4,5 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/qRYDNWXuip8',
                'audience' => 18
            ],
            [
                'id' => 23,
                'titre' => 'Django Unchained',
                'resume' => 'Dans le Sud des États-Unis avant la guerre civile, un chasseur de primes libère un esclave et lentraîne dans une mission pour retrouver sa femme et se venger des propriétaires desclaves.',
                'affiche' => '../images/films/django.jpg',
                'duree' => '2h45min',
                'realisateur_id' => 10,
                'producteur_id' => 10,
                'acteur_id' => 18,
                'annee' => 2012,
                'cote' => '4,5 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/0fUCuvNlOCg',
                'audience' => 18
            ],
            [
                'id' => 24,
                'titre' => 'Kill Bill: Vol. 1',
                'resume' => 'Une femme se réveille dun coma et se lance dans une mission de vengeance contre ceux qui ont tenté de la tuer, en particulier le leader dun gang de tueurs à gages.',
                'affiche' => '../images/films/killbill.jpg',
                'duree' => '1h51min',
                'realisateur_id' => 10,
                'producteur_id' => 10,
                'acteur_id' => 19,
                'annee' => 2003,
                'cote' => '4 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/7kSuas6mRpk',
                'audience' => 16
            ],
            [
                'id' => 25,
                'titre' => 'Kill Bill: Vol. 2',
                'resume' => 'La femme continue sa quête de vengeance en poursuivant les membres restants du gang de tueurs à gages et en cherchant à éliminer le leader.',
                'affiche' => '../images/films/killbill2.jpg',
                'duree' => '2h17min',
                'realisateur_id' => 10,
                'producteur_id' => 10,
                'acteur_id' => 19,
                'annee' => 2004,
                'cote' => '4 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/WTt8cCIvGYI',
                'audience' => 16
            ],
            [
                'id' => 26,
                'titre' => 'Once Upon a Time in Hollywood',
                'resume' => 'À Hollywood en 1969, un acteur vieillissant et sa doublure tentent de trouver leur place dans une industrie en pleine évolution, tout en étant mêlés aux événements de lépoque.',
                'affiche' => '../images/films/onceuponatime.jpg',
                'duree' => '2h41min',
                'realisateur_id' => 10,
                'producteur_id' => 6,
                'acteur_id' => 1,
                'annee' => 2019,
                'cote' => '4 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/Scf8nIJCvs4',
                'audience' => 18
            ],
            [
                'id' => 27,
                'titre' => 'Reservoir Dogs',
                'resume' => 'Un groupe de voleurs professionnels tente de découvrir le traître parmi eux après quun braquage de diamant ait mal tourné.',
                'affiche' => '../images/films/reservoirdogs.jpg',
                'duree' => '1h39min',
                'realisateur_id' => 10,
                'producteur_id' => 15,
                'acteur_id' => 15,
                'annee' => 1992,
                'cote' => '4 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/GLPJSmUHZvU',
                'audience' => 18
            ],
            [
                'id' => 28,
                'titre' => 'Jackie Brown',
                'resume' => 'Une hôtesse de lair manipulatrice, un trafiquant darmes, un détective de la police et une agente fédérale se croisent dans une histoire de crime et de tromperie.',
                'affiche' => '../images/films/jackiebrown.jpg',
                'duree' => '2h34min',
                'realisateur_id' => 10,
                'producteur_id' => 15,
                'acteur_id' => 16,
                'annee' => 1997,
                'cote' => '4 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/G7HkBDNZV7s',
                'audience' => 16
            ],
            [
                'id' => 29,
                'titre' => 'Death Proof',
                'resume' => 'Un cascadeur psychopathe chasse des jeunes femmes au volant de sa voiture meurtrière, mais il ne sait pas à qui il a affaire.',
                'affiche' => '../images/films/deathproof.jpg',
                'duree' => '1h53min',
                'realisateur_id' => 10,
                'producteur_id' => 10,
                'acteur_id' => 17,
                'annee' => 2007,
                'cote' => '3,5 étoiles',
                'categorie' => 'À revoir',
                'bandeAnnonce' => 'https://www.youtube.com/embed/ndePUePt_OE',
                'audience' => 16
            ],
            [
                'id' => 30,
                'titre' => 'The Hateful Eight',
                'resume' => 'Dans le Wyoming après la guerre civile, huit étrangers sont piégés dans un chalet pendant une tempête de neige, mais certains dentre eux ne sont pas ce quils semblent être.',
                'affiche' => '../images/films/thehatefuleight.jpg',
                'duree' => '3h8min',
                'realisateur_id' => 10,
                'producteur_id' => 10,
                'acteur_id' => 7,
                'annee' => 2015,
                'cote' => '4 étoiles',
                'categorie' => 'classique',
                'bandeAnnonce' => 'https://www.youtube.com/embed/juaP_vRyIGY',
                'audience' => 18
            ],
            [
                'id' => 31,
                'titre' => 'Barbie',
                'resume' => 'Barbie, qui vit à Barbie Land, est expulsée du pays pour être loin d\'être une poupée à l\'apparence parfaite; nayant nulle part où aller, elle part pour le monde humain et cherche le vrai bonheur.',
                'affiche' => '../images/films/barbie.webp',
                'duree' => '1h54',
                'realisateur_id' => 12,
                'producteur_id' => 12,
                'acteur_id' => 20,
                'annee' => 2023,
                'cote' => '4 étoiles',
                'categorie' => 'Autres',
                'bandeAnnonce' => 'https://www.youtube.com/embed/pBk4NYhWNMM',
                'audience' => 8
            ],
            [
                'id' => 32,
                'titre' => 'La casa de Papel',
                'resume' => 'Huit voleurs mènent une prise d\'otage dans la Maison royale de la Monnaie d\'Espagne, tandis qu\'un génie criminel manipule la police pour mettre son plan à exécution.',
                'affiche' => '../images/films/lacasadepapel.jpg',
                'duree' => '5 saisons',
                'realisateur_id' => 29,
                'producteur_id' => 29,
                'acteur_id' => 28,
                'annee' => 2017,
                'cote' => '5 étoiles',
                'categorie' => 'tendance',
                'bandeAnnonce' => 'https://www.youtube.com/embed/_InqQJRqGW4',
                'audience' => 16
            ]

        ]);
            
    }
}
